apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: redis-operator
  app.kubernetes.io/instance: redis-operator

components:
  - ../../components/monitoring/
  - ../../components/version/

resources:
  - ../default/
