apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
spec:
  template:
    spec:
      containers:
        - name: redis-operator
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
