apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: redis-operator

resources:
  - https://raw.githubusercontent.com/spotahome/redis-operator/v1.1.1/manifests/databases.spotahome.com_redisfailovers.yaml
  - deployment.yaml
